more RPM fixes

diff --git a/extra/rpms/el-6/SOURCES/mcomaster.init b/extra/rpms/el-6/SOURCES/mcomaster.init
--- a/extra/rpms/el-6/SOURCES/mcomaster.init
+++ b/extra/rpms/el-6/SOURCES/mcomaster.init
@@ -34,6 +34,12 @@ fi
 
 start() {
     echo -n $"Starting $prog: "
+
+    if ! [[ -f /etc/mcomaster/application.yml ]]; then
+            echo -n $"/etc/mcomaster/application.yml is missing.";
+            failure $"/etc/mcomaster/application.yml is missing.";      
+    fi
+
     if [[ $MCOMASTER_USE_THIN = 1 ]]
     then
         /usr/bin/ruby193-ruby ${MCOMASTER_HOME}/bin/thin start --user ${MCOMASTER_USER} \
